Vagrant.configure('2') do |config|
    # Disable /vagrant synced folder
    config.vm.synced_folder '.', '/vagrant', disabled: true

    config.vm.define :ubuntu16 do |ubuntu|
        ubuntu.vm.box = 'geerlingguy/ubuntu1604'
    end

    config.vm.define :debian8 do |debian|
        debian.vm.box = 'debian/jessie64'
    end

    config.vm.define :centos7 do |centos|
        centos.vm.box = 'centos/7'
    end
end
